title: Mohit Punjabi
logo: /assets/img/headshot.png
description: text below image
# show_downloads: true
theme: minima
social:
  gmail: punjabimohit99@gmail.com
  github: https://github.com/punjabi-mohit
  linkedin: https://www.linkedin.com/in/mohit-punjabi/
